# Generated by Django 5.0.6 on 2024-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.DateTimeField()),
                ('name', models.TextField(max_length=250)),
                ('league_id', models.IntegerField()),
            ],
        ),
    ]
